# Generated by Django 5.2.7 on 2025-10-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='temps',
            field=models.PositiveIntegerField(),
        ),
    ]
