# Generated by Django 4.2.30 on 2026-04-10 16:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('lang', models.CharField(choices=[('en', 'English'), ('fr', 'Francais'), ('br', 'Breton'), ('de', 'Deutsch')], default='en', max_length=2)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('datenaissance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('desc_groupage', models.CharField(max_length=100)),
                ('label_groupage', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('max_point', models.IntegerField()),
                ('seuil1', models.IntegerField()),
                ('seuil2', models.IntegerField()),
                ('max_item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('observation', models.TextField(blank=True, null=True)),
                ('max_score', models.FloatField()),
                ('itempos', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=1)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='competence/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_icon', models.ImageField(upload_to='competence/header_icons/')),
                ('schule_name', models.TextField(blank=True, null=True)),
                ('header_message', models.TextField(blank=True, null=True)),
                ('footer_message1', models.TextField(blank=True, null=True)),
                ('footer_message2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('seuil1_percent', models.FloatField(default=0.0)),
                ('seuil2_percent', models.FloatField(default=0.0)),
                ('seuil3_percent', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('scorelabel', models.CharField(blank=True, max_length=50, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('translation', models.TextField()),
            ],
            options={
                'unique_together': {('key', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ScoreRulePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorelabel', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('scorerule', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='competence.scorerule')),
            ],
        ),
        migrations.AddIndex(
            model_name='scorerule',
            index=models.Index(fields=['description'], name='scorerule_description_idx'),
        ),
        migrations.AddField(
            model_name='resultatdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competence.item'),
        ),
        migrations.AddField(
            model_name='resultatdetail',
            name='resultat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_details', to='competence.resultat'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='groupage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competence.groupagedata'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='report_catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='competence.reportcatalogue'),
        ),
        migrations.AddField(
            model_name='reportcatalogue',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competence.catalogue'),
        ),
        migrations.AddField(
            model_name='reportcatalogue',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_catalogues', to='competence.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='competence.eleve'),
        ),
        migrations.AddField(
            model_name='report',
            name='pdflayout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competence.pdflayout'),
        ),
        migrations.AddField(
            model_name='report',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='niveau',
            index=models.Index(fields=['niveau'], name='niveau_idx'),
        ),
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['matiere'], name='matiere_idx'),
        ),
        migrations.AddField(
            model_name='item',
            name='groupagedata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competence.groupagedata'),
        ),
        migrations.AddField(
            model_name='item',
            name='scorerule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competence.scorerule'),
        ),
        migrations.AddField(
            model_name='groupagedata',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competence.catalogue'),
        ),
        migrations.AddField(
            model_name='groupagedata',
            name='groupage_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competence.myimage'),
        ),
        migrations.AddIndex(
            model_name='etape',
            index=models.Index(fields=['etape'], name='etape_idx'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competence.niveau'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='professeurs',
            field=models.ManyToManyField(blank=True, related_name='eleves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competence.annee'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='etape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competence.etape'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='matiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competence.matiere'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competence.niveau'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='professeurs',
            field=models.ManyToManyField(blank=True, related_name='catalogues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='annee',
            index=models.Index(fields=['is_active'], name='annee_active_idx'),
        ),
        migrations.AddIndex(
            model_name='annee',
            index=models.Index(fields=['start_date'], name='annee_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='annee',
            index=models.Index(fields=['stop_date'], name='annee_stop_date_idx'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='scorerulepoint',
            index=models.Index(fields=['scorerule'], name='scorerulepoint_scorerule_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatdetail',
            index=models.Index(fields=['resultat'], name='resultatdetail_resultat_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatdetail',
            index=models.Index(fields=['item'], name='resultatdetail_item_idx'),
        ),
        migrations.AddIndex(
            model_name='resultat',
            index=models.Index(fields=['report_catalogue'], name='resultat_report_catalogue_idx'),
        ),
        migrations.AddIndex(
            model_name='resultat',
            index=models.Index(fields=['groupage'], name='resultat_groupage_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcatalogue',
            index=models.Index(fields=['report'], name='reportcatalogue_report_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcatalogue',
            index=models.Index(fields=['catalogue'], name='reportcatalogue_catalogue_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['eleve'], name='report_eleve_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['professeur'], name='report_professeur_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['groupagedata'], name='item_groupagedata_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['scorerule'], name='item_scorerule_idx'),
        ),
        migrations.AddIndex(
            model_name='groupagedata',
            index=models.Index(fields=['catalogue'], name='groupagedata_catalogue_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['niveau'], name='eleve_niveau_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogue',
            index=models.Index(fields=['niveau'], name='catalogue_niveau_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogue',
            index=models.Index(fields=['etape'], name='catalogue_etape_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogue',
            index=models.Index(fields=['annee'], name='catalogue_annee_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogue',
            index=models.Index(fields=['matiere'], name='catalogue_matiere_idx'),
        ),
    ]
